SEARCH_ON = "Wyszukiwanie na:"
WINDOW_TITLE = "Porównywarka produktów"
PRODUCT_BROWSER = "Wpisz nazwę produktu: "
PRODUCT_BROWSE = "Pobierz dane"
IN_PROGRESS = "Proszę czekać... Trwa zbieranie danych.."